// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// D_center
NumericMatrix D_center(NumericMatrix Dx);
RcppExport SEXP energy_D_center(SEXP DxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    __result = Rcpp::wrap(D_center(Dx));
    return __result;
END_RCPP
}
// U_center
NumericMatrix U_center(NumericMatrix Dx);
RcppExport SEXP energy_U_center(SEXP DxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    __result = Rcpp::wrap(U_center(Dx));
    return __result;
END_RCPP
}
// dcovU_stats
NumericVector dcovU_stats(NumericMatrix Dx, NumericMatrix Dy);
RcppExport SEXP energy_dcovU_stats(SEXP DxSEXP, SEXP DySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    __result = Rcpp::wrap(dcovU_stats(Dx, Dy));
    return __result;
END_RCPP
}
// mvnEstat
double mvnEstat(NumericMatrix y);
RcppExport SEXP energy_mvnEstat(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    __result = Rcpp::wrap(mvnEstat(y));
    return __result;
END_RCPP
}
// partial_dcor
NumericVector partial_dcor(NumericMatrix Dx, NumericMatrix Dy, NumericMatrix Dz);
RcppExport SEXP energy_partial_dcor(SEXP DxSEXP, SEXP DySEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    __result = Rcpp::wrap(partial_dcor(Dx, Dy, Dz));
    return __result;
END_RCPP
}
// partial_dcov
double partial_dcov(NumericMatrix Dx, NumericMatrix Dy, NumericMatrix Dz);
RcppExport SEXP energy_partial_dcov(SEXP DxSEXP, SEXP DySEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    __result = Rcpp::wrap(partial_dcov(Dx, Dy, Dz));
    return __result;
END_RCPP
}
// projection
NumericMatrix projection(NumericMatrix Dx, NumericMatrix Dz);
RcppExport SEXP energy_projection(SEXP DxSEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    __result = Rcpp::wrap(projection(Dx, Dz));
    return __result;
END_RCPP
}
// U_product
double U_product(NumericMatrix U, NumericMatrix V);
RcppExport SEXP energy_U_product(SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    __result = Rcpp::wrap(U_product(U, V));
    return __result;
END_RCPP
}
