# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

D_center <- function(Dx) {
    .Call('energy_D_center', PACKAGE = 'energy', Dx)
}

U_center <- function(Dx) {
    .Call('energy_U_center', PACKAGE = 'energy', Dx)
}

dcovU_stats <- function(Dx, Dy) {
    .Call('energy_dcovU_stats', PACKAGE = 'energy', Dx, Dy)
}

mvnEstat <- function(y) {
    .Call('energy_mvnEstat', PACKAGE = 'energy', y)
}

partial_dcor <- function(Dx, Dy, Dz) {
    .Call('energy_partial_dcor', PACKAGE = 'energy', Dx, Dy, Dz)
}

partial_dcov <- function(Dx, Dy, Dz) {
    .Call('energy_partial_dcov', PACKAGE = 'energy', Dx, Dy, Dz)
}

projection <- function(Dx, Dz) {
    .Call('energy_projection', PACKAGE = 'energy', Dx, Dz)
}

U_product <- function(U, V) {
    .Call('energy_U_product', PACKAGE = 'energy', U, V)
}

